apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cve-portal
spec:
  rules:
    - host: cve-portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cve-portal-ui
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cve-portal-api
                port:
                  number: 8000

